---
# tasks file for nginx
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: modify nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy default.conf
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: validate nginx's configuration

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: adjust upstream based on host's ip
  lineinfile:
    dest: /etc/nginx/conf.d/default.conf
    regexp: "{{ ansible_ssh_host }}"
    line: "    server 127.0.0.1:{{ service_port }};"
  notify: reload nginx
