---
  - hosts: all
    become: true
    become_user: root
    roles:
      - nginx
      - minio
    vars:
      hosts_ip: 192.168.57
      minio_access_key: testovoe
      minio_secret_key: sekretnoe
