galaxy_info:
  author: Artur Sholomko 
  description: Depends
  company: Quadcode 
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1
  galaxy_tags: 
    - minio 

dependencies: []
