---
# handlers file for nginx
- name: validate nginx's configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted
