---
# tasks file for minio
- name: create minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: create minio user
  user:
    name: "{{ minio_user }}"
    groups: "{{ minio_group }}"

- name: mkdir minio's bin dir
  file:
    path: "{{ minio_dest_bin }}"
    state: directory

- name: download minio's bin
  get_url:
    url: "{{ minio_download_url }}"
    dest: "{{ minio_bin }}" 
    mode: 0755

- name: create minio's export dir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  loop:
    - /home/minio/export1
    - /home/minio/export2

- name: copy defaults options template
  template:
    src: minio_opt.j2
    dest: /etc/default/{{ minio_service }}
  notify: restart minio

- name: copy systemd service template
  template:
    src: minio.service.j2
    dest: /etc/systemd/system/{{ minio_service }}.service
  notify: restart minio

- name: start minio
  systemd: name={{ minio_service }} state=started enabled=yes daemon_reload=yes
